### ISSUE TITLE
Confrontapdf compiling steps

### ISSUE THREAD

**Issue by rayenmhamdi** [lbellonda/ConfrontaPDF#6]
Hi.
I really admire your work and i want to add some features.
But when i follow your readme steps i cant.
Please can you provide me with more detailed steps (with links of qt , poppler) and espacially how to install poppler and get the header files for qt.
This is my private email : rayenmhamdi94@gmail.com

**Comment by lbellonda** [comment]
Hello, what operating system and version are you using to compile?

**Comment by rayenmhamdi** [comment]
Windows 10.
I need to know what compile i should use. Which version of qt. And how to install poppler and have the headers files.

Thank you

**Comment by lbellonda** [comment]
The setup I used is for 32 bit programs on Windows 7 some time ago.
Maybe in the meantime the things could be changed.

The compiler/Qt I used is Qt 5.3 with QtCreator for mingw-32. You can download it from Qt site.
Poppler is the binary distribution poppler-0.32.0-mingw32-1.zip found on SourceForge; I unzipped it in a folder
and it contains headers and libraries.
The site could be https://sourceforge.net/projects/poppler-qt5-mingw32.

You can unzip it on ../poppler-win/ folder as stated in confrontapdf.pri: 
_exists(../poppler-win/poppler/include)_

Best regards

**Comment by rayenmhamdi** [comment]
Thank youuu very much
